### ISSUE TITLE
Accept multiple sitemaps

### ISSUE THREAD

**Issue by massimo-me** [skuola/SitemapBundle#10]
Accept multiple sitemaps

``` yml
skuola_sitemap:
    scheme: http
    host: %domain%
    db_driver: orm
    test_blog:
        base_url: http://%domain%/sitemaps/blog/
        index_path: %kernel.root_dir%/../web/sitemaps/blog/sitemap_index.xml
        path:  %kernel.root_dir%/../web/sitemaps/blog/sitemap.xml
        routes:
               ...........
    blog:
        base_url: http://%domain%/sitemaps/blog/
        index_path: %kernel.root_dir%/../web/sitemaps/blog/sitemap_index.xml
        path:  %kernel.root_dir%/../web/sitemaps/blog/sitemap.xml
        routes:
             ............
```
